version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            -  MONGODB_USER=${MONGO_USER} 
            -  MONGODB_PASS=${MONGO_PASSWORD}
        command: mongod --smallfiles  
        ports:
            - '27017:27017'
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER} 
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
        ports:
            - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
        links:
            - 'mongodb:mongo'